### PR TITLE
Nexus 7 (grouper)(tilapia) binaries for Android 5.1 LMY47D

### PR DESCRIPTION
**Pull request by jrizzoli**
Signed-off-by: linuxxxxx joey@cyanogenmoditalia.it

### CODE REVIEW

**Comment by dhacker29** [comment]
Grouper binaries are already updated to posted blobs, not sure where those changes come from. Also, you are overwriting the change to include tf_daemon

**Comment by jrizzoli** [comment]
These are from https://developers.google.com/android/nexus/drivers

**Comment by linuxxxxx** [comment]
BTW I'll update this to update just tilapia

**Comment by thoemy** [comment]
@dhacker29 You missed the tf_daemon changes to grouper/device-partial.mk and grouper/proprietary/Android.mk that are displayed in this pull request.

**Comment by thoemy** [comment]
The question is whether or not we need the tf_daemon. Because it's still in the 5.1 init.grouper.rc

**Comment by dhacker29** [comment]
It's never been in the make files for grouper from aosp blobs but you can see in the history where it was added. It is in factory image

**Comment by thoemy** [comment]
Oh, then yell at me the next time I remove it unknowingly ;). I actually didn't see that you fixed it.

**Pull request closed without merging**
