### PR TITLE
Add shield_common back with console mode and leanback ime.

### PR DESCRIPTION
**Pull request by webgeek1234**
With the vendor_init patch, console mode is now usable. Also add leanback ime to save time on foster later.

### CODE REVIEW

**Comment by webgeek1234** [comment]
Will a leanback app update on a non-leanback build (which is what my cm-12.1 foster builds are since the android tv code is pretty non-existent before M)? And if it isn't system signed, will it be used as the default keyboard? Foster wasn't building any other keyboards.

I'd have to repull the apk to use presigned because that one is from the foster stock image which has an external odex. I had to de-odex, repackage, then sign on build to get it to work here. Unless there's a better place I can get the apk which will work more generically.

**Comment by dhacker29** [comment]
All the android TV code was in aosp with 5.0 and fugu release. But yeah if you have normal playstore it probably wouldn't update it... Not sure. There are no libs so the one from vendor/asus/fugu should work.

**Comment by dhacker29** [comment]
And yes fugu uses it as default keyboard with PRESIGNED

**Comment by webgeek1234** [comment]
Hmm... When I built full TV mode, adding tvsettings, stuff broke horribly, so I left that out and it 'works', but I still have problems that I can't get rid of, so I'm pretty much just waiting on Nvidia to drop M, then I'll push for cm-13.0 support. Meh, I can just drop Leanback IME for now and worry about it when I push in foster, hang on a sec. The other app isn't on the store, so it will never get updated unless I do it manually.

**Comment by dhacker29** [comment]
I can merge this as is if it works and update it later, I think I am going to get the Shield TV and work on it for cm-13

**Comment by webgeek1234** [comment]
The remaining apk is for roth and shieldtablet. And yes, works as intended. Was just trying to sneak in the extra, but oh well.

The help would be welcome on cm-13.0. Current code is on CM-Shield, but doesn't even get to init last I tried. Tried the same stuff that got roth and shieldtablet booting, but no go. Will work on it more after the start of the year.

**Comment by webgeek1234** [comment]
Can someone please merge this? I'd like to get it in my nightly builds.

**Pull request merged**
